from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path
from statistics import mean, pstdev
from typing import Any

from PIL import Image
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score, recall_score
from sklearn.model_selection import StratifiedShuffleSplit
import torch
from torch import nn
from torch.utils.data import DataLoader, Dataset
from torchvision import models, transforms

from eviosahs.models import (
    STRUCTURED_FEATURE_NAMES,
    ensure_parent_dir,
    load_prediction_records,
    now_iso,
    read_jsonl,
    write_json_atomic,
    write_jsonl,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run classical OSAHS baselines under a fixed CV or single holdout protocol.")
    parser.add_argument("--manifest-jsonl", required=True, help="Manifest generated by prepare_dataset.py")
    parser.add_argument("--folds-json", default=None, help="folds.json generated by prepare_dataset.py; required only when --split-mode=cv")
    parser.add_argument("--output-dir", required=True, help="Output directory for this baseline")
    parser.add_argument(
        "--split-mode",
        choices=["cv", "holdout"],
        default="cv",
        help="cv uses precomputed folds.json; holdout uses a single fixed stratified split for quick experiments.",
    )
    parser.add_argument("--holdout-ratio", type=float, default=0.2, help="Test ratio for --split-mode=holdout")
    parser.add_argument("--seed", type=int, default=42, help="Random seed for holdout split")
    parser.add_argument(
        "--method",
        required=True,
        choices=["clinical_tree", "image_resnet50", "image_vit_b16", "image_clinical_late_fusion"],
        help="Baseline method to run.",
    )
    parser.add_argument("--epochs", type=int, default=8, help="Training epochs for image-based baselines")
    parser.add_argument("--batch-size", type=int, default=16, help="Batch size for image-based baselines")
    parser.add_argument("--num-workers", type=int, default=0, help="Dataloader workers")
    parser.add_argument("--lr", type=float, default=1e-4, help="Learning rate for image-based baselines")
    parser.add_argument("--weight-decay", type=float, default=1e-4, help="Weight decay for image-based baselines")
    parser.add_argument("--image-size", type=int, default=224, help="Input image size")
    parser.add_argument("--device", default="cuda:0" if torch.cuda.is_available() else "cpu", help="Torch device")
    parser.add_argument("--train-backbone", action="store_true", help="Finetune the image backbone instead of training only the head")
    parser.add_argument("--pretrained", action="store_true", help="Use torchvision pretrained weights when available locally")
    return parser.parse_args()


def build_split_payloads(args: argparse.Namespace, manifest: list[dict[str, Any]]) -> list[dict[str, Any]]:
    if args.split_mode == "cv":
        if not args.folds_json:
            raise ValueError("--folds-json is required when --split-mode=cv")
        return json.loads(Path(args.folds_json).read_text(encoding="utf-8"))["folds"]

    labels = [record["binary_label"] for record in manifest]
    splitter = StratifiedShuffleSplit(n_splits=1, test_size=args.holdout_ratio, random_state=args.seed)
    train_idx, test_idx = next(splitter.split(manifest, labels))
    return [
        {
            "fold_index": 0,
            "split_mode": "holdout",
            "train_indices": [int(index) for index in train_idx],
            "test_indices": [int(index) for index in test_idx],
            "train_size": len(train_idx),
            "test_size": len(test_idx),
        }
    ]


def build_summary(args: argparse.Namespace, method: str, backend_name: str, fold_metrics: list[dict[str, Any]]) -> dict[str, Any]:
    summary: dict[str, Any] = {
        "created_at": now_iso(),
        "method": method,
        "backend": backend_name,
        "split_mode": args.split_mode,
        "arguments": vars(args),
        "fold_metrics": fold_metrics,
    }
    if args.split_mode == "cv":
        summary["cv_summary"] = aggregate_fold_reports(fold_metrics)
    elif fold_metrics:
        summary["single_run"] = fold_metrics[0]
    return summary


def binary_metrics_from_arrays(y_true: list[int], y_pred: list[int]) -> dict[str, Any]:
    acc = accuracy_score(y_true, y_pred) if y_true else 0.0
    sens = recall_score(y_true, y_pred, pos_label=1, zero_division=0) if y_true else 0.0
    spec = recall_score(y_true, y_pred, pos_label=0, zero_division=0) if y_true else 0.0
    f1 = f1_score(y_true, y_pred, pos_label=1, zero_division=0) if y_true else 0.0
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred, labels=[0, 1]).ravel() if y_true else (0, 0, 0, 0)
    return {
        "tp": int(tp),
        "tn": int(tn),
        "fp": int(fp),
        "fn": int(fn),
        "report": {
            "Accuracy (%)": round(acc * 100, 4),
            "Sensitivity (%)": round(sens * 100, 4),
            "Specificity (%)": round(spec * 100, 4),
            "F1-Score (%)": round(f1 * 100, 4),
        },
    }


def aggregate_fold_reports(fold_metrics: list[dict[str, Any]]) -> dict[str, Any]:
    keys = ["Accuracy (%)", "Sensitivity (%)", "Specificity (%)", "F1-Score (%)"]
    summary: dict[str, Any] = {"fold_count": len(fold_metrics)}
    for key in keys:
        values = [float(metrics["report"][key]) for metrics in fold_metrics]
        summary[key] = {
            "mean": round(mean(values), 4) if values else 0.0,
            "std": round(pstdev(values), 4) if len(values) > 1 else 0.0,
            "values": values,
        }
    return summary


def label_to_int(label: str) -> int:
    return 1 if str(label).lower() == "yes" else 0


class ManifestImageDataset(Dataset):
    def __init__(self, records: list[dict[str, Any]], transform: transforms.Compose, include_structured: bool = False) -> None:
        self.records = records
        self.transform = transform
        self.include_structured = include_structured

    def __len__(self) -> int:
        return len(self.records)

    def __getitem__(self, index: int) -> dict[str, Any]:
        record = self.records[index]
        image = Image.open(record["image_path"]).convert("RGB")
        item = {
            "image": self.transform(image),
            "label": torch.tensor(label_to_int(record["binary_label"]), dtype=torch.long),
            "image_name": record["image_name"],
            "gold_label": record["binary_label"],
        }
        if self.include_structured:
            item["structured"] = torch.tensor(
                [float(record[name]) for name in STRUCTURED_FEATURE_NAMES],
                dtype=torch.float32,
            )
        return item


def collate_batch(batch: list[dict[str, Any]]) -> dict[str, Any]:
    collated = {
        "image": torch.stack([item["image"] for item in batch]),
        "label": torch.stack([item["label"] for item in batch]),
        "image_name": [item["image_name"] for item in batch],
        "gold_label": [item["gold_label"] for item in batch],
    }
    if "structured" in batch[0]:
        collated["structured"] = torch.stack([item["structured"] for item in batch])
    return collated


def build_transforms(image_size: int) -> tuple[transforms.Compose, transforms.Compose]:
    train_transform = transforms.Compose(
        [
            transforms.Resize((image_size, image_size)),
            transforms.RandomHorizontalFlip(),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
        ]
    )
    eval_transform = transforms.Compose(
        [
            transforms.Resize((image_size, image_size)),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
        ]
    )
    return train_transform, eval_transform


def freeze_backbone_parameters(model: nn.Module, head_prefixes: tuple[str, ...]) -> None:
    for name, parameter in model.named_parameters():
        parameter.requires_grad = any(name.startswith(prefix) for prefix in head_prefixes)


def build_image_backbone(method: str, pretrained: bool, train_backbone: bool) -> nn.Module:
    if method == "image_resnet50":
        weights = models.ResNet50_Weights.DEFAULT if pretrained else None
        model = models.resnet50(weights=weights)
        in_features = model.fc.in_features
        model.fc = nn.Linear(in_features, 2)
        if not train_backbone:
            freeze_backbone_parameters(model, ("fc",))
        return model

    if method == "image_vit_b16":
        weights = models.ViT_B_16_Weights.DEFAULT if pretrained else None
        model = models.vit_b_16(weights=weights)
        in_features = model.heads.head.in_features
        model.heads.head = nn.Linear(in_features, 2)
        if not train_backbone:
            freeze_backbone_parameters(model, ("heads",))
        return model

    raise ValueError(f"Unsupported image method: {method}")


class LateFusionResNet50(nn.Module):
    def __init__(self, pretrained: bool, train_backbone: bool, structured_dim: int) -> None:
        super().__init__()
        weights = models.ResNet50_Weights.DEFAULT if pretrained else None
        backbone = models.resnet50(weights=weights)
        image_dim = backbone.fc.in_features
        backbone.fc = nn.Identity()
        self.backbone = backbone
        self.structured_mlp = nn.Sequential(
            nn.Linear(structured_dim, 32),
            nn.ReLU(),
            nn.Dropout(p=0.1),
        )
        self.classifier = nn.Sequential(
            nn.Linear(image_dim + 32, 128),
            nn.ReLU(),
            nn.Dropout(p=0.2),
            nn.Linear(128, 2),
        )
        if not train_backbone:
            freeze_backbone_parameters(self.backbone, tuple())
            for parameter in self.backbone.parameters():
                parameter.requires_grad = False

    def forward(self, image: torch.Tensor, structured: torch.Tensor) -> torch.Tensor:
        image_features = self.backbone(image)
        structured_features = self.structured_mlp(structured)
        merged = torch.cat([image_features, structured_features], dim=1)
        return self.classifier(merged)


def train_image_model(
    model: nn.Module,
    train_loader: DataLoader,
    test_loader: DataLoader,
    device: str,
    epochs: int,
    lr: float,
    weight_decay: float,
    *,
    include_structured: bool = False,
) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    model = model.to(device)
    optimizer = torch.optim.AdamW([parameter for parameter in model.parameters() if parameter.requires_grad], lr=lr, weight_decay=weight_decay)
    criterion = nn.CrossEntropyLoss()

    for _ in range(epochs):
        model.train()
        for batch in train_loader:
            optimizer.zero_grad(set_to_none=True)
            image = batch["image"].to(device)
            labels = batch["label"].to(device)
            if include_structured:
                logits = model(image, batch["structured"].to(device))
            else:
                logits = model(image)
            loss = criterion(logits, labels)
            loss.backward()
            optimizer.step()

    predictions: list[dict[str, Any]] = []
    gold_labels: list[int] = []
    predicted_labels: list[int] = []
    model.eval()
    with torch.inference_mode():
        for batch in test_loader:
            image = batch["image"].to(device)
            if include_structured:
                logits = model(image, batch["structured"].to(device))
            else:
                logits = model(image)
            pred = logits.argmax(dim=1).detach().cpu().tolist()
            for image_name, gold_label, pred_label in zip(batch["image_name"], batch["gold_label"], pred):
                gold_int = label_to_int(gold_label)
                gold_labels.append(gold_int)
                predicted_labels.append(int(pred_label))
                predictions.append(
                    {
                        "image_path": image_name,
                        "binary_label": gold_label,
                        "predicted_label": "yes" if int(pred_label) == 1 else "no",
                        "match": gold_int == int(pred_label),
                        "parse_status": "classifier",
                        "final_response": f"classifier_prediction={pred_label}",
                    }
                )
    return predictions, binary_metrics_from_arrays(gold_labels, predicted_labels)


def run_clinical_tree(train_records: list[dict[str, Any]], test_records: list[dict[str, Any]]) -> tuple[list[dict[str, Any]], dict[str, Any], str]:
    try:
        from xgboost import XGBClassifier

        classifier: Any = XGBClassifier(
            n_estimators=300,
            max_depth=4,
            learning_rate=0.05,
            subsample=0.9,
            colsample_bytree=0.9,
            reg_lambda=1.0,
            objective="binary:logistic",
            eval_metric="logloss",
            random_state=42,
        )
        backend = "xgboost"
    except Exception:
        classifier = HistGradientBoostingClassifier(max_depth=4, learning_rate=0.05, random_state=42)
        backend = "hist_gradient_boosting"

    x_train = [[float(record[name]) for name in STRUCTURED_FEATURE_NAMES] for record in train_records]
    y_train = [label_to_int(record["binary_label"]) for record in train_records]
    x_test = [[float(record[name]) for name in STRUCTURED_FEATURE_NAMES] for record in test_records]
    y_test = [label_to_int(record["binary_label"]) for record in test_records]

    classifier.fit(x_train, y_train)
    predictions_int = [int(value) for value in classifier.predict(x_test)]
    predictions = [
        {
            "image_path": record["image_name"],
            "binary_label": record["binary_label"],
            "predicted_label": "yes" if pred == 1 else "no",
            "match": label_to_int(record["binary_label"]) == pred,
            "parse_status": backend,
            "final_response": f"{backend}_prediction={pred}",
        }
        for record, pred in zip(test_records, predictions_int)
    ]
    return predictions, binary_metrics_from_arrays(y_test, predictions_int), backend


def main() -> None:
    args = parse_args()
    manifest = read_jsonl(args.manifest_jsonl)
    folds = build_split_payloads(args, manifest)
    output_dir = Path(args.output_dir)
    train_transform, eval_transform = build_transforms(args.image_size)

    fold_metrics: list[dict[str, Any]] = []
    all_predictions: list[dict[str, Any]] = []
    backend_name = args.method

    for fold in folds:
        fold_index = int(fold["fold_index"])
        fold_root = output_dir / f"fold_{fold_index}"
        train_records = [manifest[index] for index in fold["train_indices"]]
        test_records = [manifest[index] for index in fold["test_indices"]]

        if args.method == "clinical_tree":
            predictions, metrics, backend_name = run_clinical_tree(train_records, test_records)
        elif args.method in {"image_resnet50", "image_vit_b16"}:
            model = build_image_backbone(args.method, pretrained=args.pretrained, train_backbone=args.train_backbone)
            train_dataset = ManifestImageDataset(train_records, train_transform, include_structured=False)
            test_dataset = ManifestImageDataset(test_records, eval_transform, include_structured=False)
            train_loader = DataLoader(train_dataset, batch_size=args.batch_size, shuffle=True, num_workers=args.num_workers, collate_fn=collate_batch)
            test_loader = DataLoader(test_dataset, batch_size=args.batch_size, shuffle=False, num_workers=args.num_workers, collate_fn=collate_batch)
            predictions, metrics = train_image_model(
                model,
                train_loader,
                test_loader,
                args.device,
                args.epochs,
                args.lr,
                args.weight_decay,
                include_structured=False,
            )
        elif args.method == "image_clinical_late_fusion":
            model = LateFusionResNet50(
                pretrained=args.pretrained,
                train_backbone=args.train_backbone,
                structured_dim=len(STRUCTURED_FEATURE_NAMES),
            )
            train_dataset = ManifestImageDataset(train_records, train_transform, include_structured=True)
            test_dataset = ManifestImageDataset(test_records, eval_transform, include_structured=True)
            train_loader = DataLoader(train_dataset, batch_size=args.batch_size, shuffle=True, num_workers=args.num_workers, collate_fn=collate_batch)
            test_loader = DataLoader(test_dataset, batch_size=args.batch_size, shuffle=False, num_workers=args.num_workers, collate_fn=collate_batch)
            predictions, metrics = train_image_model(
                model,
                train_loader,
                test_loader,
                args.device,
                args.epochs,
                args.lr,
                args.weight_decay,
                include_structured=True,
            )
        else:
            raise ValueError(f"Unsupported method: {args.method}")

        for record in predictions:
            record["fold_index"] = fold_index
        fold_metrics.append({"fold_index": fold_index, **metrics})
        all_predictions.extend(predictions)
        write_jsonl(predictions, fold_root / "predictions.jsonl")
        write_json_atomic({"fold_index": fold_index, **metrics}, fold_root / "metrics.json")

    cv_summary = build_summary(args, args.method, backend_name, fold_metrics)
    write_jsonl(all_predictions, output_dir / "predictions.jsonl")
    metrics_filename = "cv_metrics.json" if args.split_mode == "cv" else "single_run_metrics.json"
    write_json_atomic(cv_summary, output_dir / metrics_filename)
    print(f"Completed {args.method}: {output_dir / metrics_filename}")


if __name__ == "__main__":
    main()
